### ISSUE TITLE
Frequency of sent package

### ISSUE THREAD

**Issue by AndersSpringborg** [steinwurf/steinloss#30]
Packets are sent at a frequency, with a blocking sleep function, between transmissions. This approach does not work at a high frequency, as the sleep call is expensive. An alternative solution, could be some kind of bucket solution. See https://www.geeksforgeeks.org/leaky-bucket-algorithm/

**Comment by mortenvp** [comment]
I think maybe what happens is that the socket sendto call is blocking so basically the timeout triggers and then we call send https://github.com/steinwurf/steinloss/blob/master/steinloss/server.py#L144 this also takes some time - so the frequency at which we send packets cannot be maintained. 

Instead we may want to decouple the timeout and the sendto function such that they can run independently e.g. via something like this:

```
    def send_datagram(self, packet_number):

        async def _send_datagram(packet_number):
            timestamp = time.time_ns()

            self.transport.sendto(write_packet(
                packet_number=packet_number, timestamp=timestamp))

        loop = asyncio.get_event_loop()
        loop.create_task(_send_datagram(packet_number=packet_number))
```
The function `send_datagram` is triggered by the timeout - but then instead of calling sendto there we make another async task to do that actual sending. This way we immediately can schedule another asyncio.sleep.

Hope it makes sense :)

**Comment by mortenvp** [comment]
Just to clarify 🙂 the speed is defined in megabit (Mb/s) or megabyte (MB/s)? 

Also you set it to 16 but only get 6, is that correctly understood?
